development:
  adapter: postgresql
  database: mattandjjowedding_dev
  host: localhost
  username:
  password:

test:
  adapter: postgresql
  database: mattandjjowedding_test
  host: localhost
  username:
  password:
